### PR TITLE
Notify the UI to update SelectedIndex

### PR DESCRIPTION
**Pull request by timunie**
You replace the Items. This time the selection is also lost. If we just RaisePropertyChanged for the selection, it will update selected item.

### CODE REVIEW

**Comment by Mrcubix** [comment]
This is quite odd, this feels like something that should had been done within the whatever handle `Items`

Edit: well nvm, i make more sense for the control itself to handle that

**Comment by timunie** [comment]
Feel free to open a PR in Avalonia if you know how to handle this better. I think PRs are welcome if they don't lead to any other drawbacks I don't know yet. 

Fyi: iirc WPF has the same behavior here.

**Comment by Mrcubix** [comment]
It seem like the issue is also present on linux.
Which lead me to believe the issue is within Avalonia's implementation, unless they started using WPF's implementation after that one issue was closed for merge, i'll try to check it out later.

As for this, it probably need to be moved in the setter of `SomeDict` but that's something i can do on my own now, i'll merge as a workround.

**Comment by timunie** [comment]
It's for sure in Avalonias logic. Avalonia does not base on WPF, it was just an info for you.

**Pull request merged**
